#!/usr/bin/env sh

player=$(~/.scripts/polybar/get-player)

if [ $? -eq 0 ]
then
    # copy to clipboard with xclip
    printf $(playerctl -p $player metadata xesam:url) | xclip -selection c
    # send ipc msg to bar to change the copy icon to ✓
    polybar-msg hook a-copy-url 2
else
    # send ipc msg to bar to change the copy icon to ❌
    polybar-msg hook a-copy-url 3
fi

# wait a second
sleep 1
# revert icon back to clipboard
polybar-msg hook a-copy-url 1
