#!/usr/bin/env sh

for item in $(playerctl -ls)
do if [ "$(playerctl -p $item status)" = "Playing" ]
    then player=$item
    fi
done

if [ $(expr length "$player") -eq 0 ]
then 
    exit 1
else
    echo "$player" | cut -f1 -d '.'
fi
