#!/usr/bin/env sh

prio_player="ncspot"

player=$(~/.scripts/polybar/get-player)

if [ $? -eq 0 ]
then 
    # pause the player
    playerctl -p $player pause
    # send ipc msg to bar to change to pause -> play icon displayed
    polybar-msg hook a-plpato 1
else
# polybar-msg hook copy-audio-url 3
    for item in $(playerctl -ls)
    do if [ "$item" == "$prio_player" ]
        then 
        # play on prior device
            playerctl -p $prio_player play
            # send ipc msg to bar to change to play -> pause icon displayed
            polybar-msg hook a-plpato 2
            sleep 1
            exit
        fi
    done
    # play on first found device (let playerctl decide)
    playerctl play
    # send ipc msg to bar to change to play -> pause icon displayed
    polybar-msg hook a-plpato 2
fi

polybar-msg hook a-volume 1
