#!/usr/bin/env sh

increment="0.01"
prio_player="ncspot"
player=$(~/.scripts/polybar/get-player)

if [ $# -eq 0 ]; then
    echo "No arguments supplied"
    exit
else 
    if [ $1 -eq 1 ]
    then operator="+"
    else operator="-"
    fi
fi

for item in $(playerctl -l)
do if [ "$item" == "$prio_player" ]
    then 
    # play on prior device
        playerctl -p $prio_player volume $(echo "$(playerctl -p $player volume) $operator $increment" | bc)
        polybar-msg hook a-volume 1
        exit
    fi
done
# next on first found device (let playerctl decide)
playerctl -p volume $(echo "$(playerctl volume) $operator $increment" | bc)
polybar-msg hook a-volume 1
