#!/bin/sh

wal -c
wal -qi /usr/share/pixmaps/wallpaper.jpg
echo "Updated pywal colors"

oomox-cli /opt/oomox/scripted_colors/xresources/xresources -o pywal > /dev/null
echo "Updated gtk-theme"

# update the firefox theme
pywalfox update > /dev/null
echo "Updated firefox"

# updated the telegram color palette
~/.telegram-palette-gen/telegram-palette-gen --wal > /dev/null
echo "Updated telegram palette (needs manuale updated)"
