#!/bin/bash
if [ $(echo $?) -eq 1 ]
then 
    notify_response=$(
        ~/.local/bin/notify-send.py \
            "grim: Screenshot failed" \
            "filename: $1" \
            --action copy:"Copy filename to clipboard"
    )
    readarray -t notify_response <<<"$notify_response"
    if [ "$notify_response" = "copy" ]
    then echo $1 | wl-copy
        notify-send "Copied"
    fi
    exit
fi

wl-copy < $1

notify_response=$(
    ~/.local/bin/notify-send.py \
        "Screenshot saved to clipboard" \
        "Location: $1" \
        --action open:Open edit:Edit
)

readarray -t notify_response <<<"$notify_response"

if [ "$notify_response" = "edit" ]
then swappy -f "$1"
    else if [ "$notify_response" = "open" ]
    then nemo "$1"
    fi
fi
