#!/bin/sh

cd /

if [ $# -eq 0 ]; then
    echo "No arguments supplied"
    exit
else 
    if [ -e $1 ]; then
        echo "Wallpaper found"

        sudo rm -f /usr/share/pixmaps/wallpaper.jpg
        sudo ln -s $1 /usr/share/pixmaps/wallpaper.jpg
        echo "Updated wallpaper"

        ~/.scripts/rwal $1
        echo "Update done"
    else
        echo "File doesn't exist or provided path isn't absolute"
        exit
    fi
fi
